### ISSUE TITLE
Change prefixed property values with original property, when changed

### ISSUE THREAD

**Issue by codeofsumit** [mikaeljorhult/brackets-autoprefixer#15]
It would be a nice feature if Autoprefixer would add changes, done to the original property.

Example:

Autoprefixer changes this:

```
transform: rotate(45deg);
```

to this:

```
 -webkit-transform: rotate(45deg);
 -ms-transform: rotate(45deg);
transform: rotate(45deg);
```

So when i change `transform: rotate(45deg);` to `transform: rotate(90deg);`, Autoprefixer could assign those changes to the prefixed properties as well.
This is especially useful for complex animations and transitions.

**Comment by xycris** [comment]
i am looking forward to this feature (:

**Comment by mikaeljorhult** [comment]
This is a bit out of scope for this plugin. I think it would be better served as a separate plugin.
