### ISSUE TITLE
integration with less compiler

### ISSUE THREAD

**Issue by FezVrasta** [mikaeljorhult/brackets-autoprefixer#25]
Would be nice to make this extension works even with LESS or call it when some CSS file changes in the project (in this way when I compile LESS I get the CSS autoprefixed, without have the prefixes in the LESS soruce, it would be very AWESOME).

Thanks!

**Comment by mkurz** [comment]
@mikaeljorhult Have you thought about this issue already?
I agree with @FezVrasta - I also suggest to add an "auto detect file changes" feature which simply runs autoprefixer as soon as a .css file changes.

**Comment by mikaeljorhult** [comment]
That might be possible. Please open a new issue for it and I'll look into implementing it.

**Comment by mkurz** [comment]
@mikaeljorhult Thanks for the reply - I added #35. It would be awesome if you could find some time for this (or similar) feature as it seems many people would benefit from it.
