### ISSUE TITLE
Mozilla & Opera

### ISSUE THREAD

**Issue by GBratsos** [mikaeljorhult/brackets-autoprefixer#32]
Good job! :D
Does this addon support those vendor's prefixes too?

On save it only adds webkit and ms prefixes. I went to Edit -> Autoprefixer Settings but how can i add a browser in order to get and use automatically those prefixes too?

Thanks in advance.

**Comment by mikaeljorhult** [comment]
Yes, it does add the Mozilla and Opera vendor prefixes as well if needed depending on which browser you target. You add browsers in the settings, with for example `Firefox > 20`.
