### ISSUE TITLE
CSS file won't save. 

### ISSUE THREAD

**Issue by apolloinfinity** [mikaeljorhult/brackets-autoprefixer#33]
I already debugged Brackets by reloading Brackets without extensions. I uninstalled Autoprefixer and my CSS does save. I reloaded Autoprefixer again and it does not allow me to save unless I quit Brackets. This problem is on a Mac OS X Yosemite.

**Comment by rcdavis4** [comment]
I'm having a similar problem. Trying to save with 'auto prefix on save' sends program into an infinite loop that won't save or auto prefix. In my activity monitor the brackets helper jumped up to 97% cpu usage. I too am on Mac Yosemite.

**Comment by mikaeljorhult** [comment]
This should be resolved with version 0.6.0 that was just released.

**Comment by mikaeljorhult** [comment]
Upgrading and resetting settings have solved similar problem (see #38).
Please reopen if you're still having problems.
