### ISSUE TITLE
 Add browsers in setup #question

### ISSUE THREAD

**Issue by jihadjo** [mikaeljorhult/brackets-autoprefixer#34]
Hi, 
How do I add a new browser in the settings?
How to formulate it?

User Agent..?
Tks you for your help

**Comment by andresorjuela** [comment]
I had the same question. I tried adding them by name Chrome, Safari, Internet Explorer... but I could not get it to work. Do I need to add some kind of version number or is there are code for each? I looked in the wiki and then here. Any help would be greatly appreciated. I'm very happy to see this extension to Brackets!

**Comment by MauriceBuiten** [comment]
At the moment the code is not working at all, maybe try it later... (in a few weeks maybe?)

**Comment by mikaeljorhult** [comment]
Autoprefixer is using [Browserlist](https://github.com/ai/browserslist) for defining which browsers to targets. Their project readme contains all the supported names and syntax.

There were a problem when specifying browser that was resolved in version 0.6.0 of the extension.
