### ISSUE TITLE
Auto detect CSS file changes

### ISSUE THREAD

**Issue by mkurz** [mikaeljorhult/brackets-autoprefixer#35]
Please add an "auto detect file changes" feature - which simply runs autoprefixer as soon as a `.css` file changes (or gets created). With such a feature people could have following workflow:
User edits `.less`/`.sass` file -> less/sass compiler generates `.css` file -> autoprefixer plugin detects (this) change (or the newly created css file) and processes file.

You could add a setting as well:
![untitled](https://cloud.githubusercontent.com/assets/644927/6277111/3c2c738a-b88c-11e4-9ac4-13234b5c3bc9.png)

This feature would actually fix #25 (and probably #31, #29, #5).

**Comment by mkurz** [comment]
Also #16 would probably be fixed with such a feature.

**Comment by mkurz** [comment]
@mikaeljorhult Do you think you will implement this anytime soon?

**Comment by mikaeljorhult** [comment]
It's next on my list to implement but I can't promise a date for the release. Any help/pull requests on the feature would be appreciated.

**Comment by mkurz** [comment]
Cool, thanks! I am very busy now - but if I ever find some time I will have a look.

**Comment by kangrian** [comment]
Best support for this project. #awesome

**Comment by mikaeljorhult** [comment]
@mkurz: This feature is now in the master branch. Still got some testing before release but if you want to give it ago now please let me know if you run into any problems.

**Comment by mkurz** [comment]
@mikaeljorhult Sound great! I am very busy right now - but if I find time I will test it.
Thank you very much anyway!
