### ISSUE TITLE
Issue with brackets.json preferences?

### ISSUE THREAD

**Issue by jpstack** [mikaeljorhult/brackets-autoprefixer#37]
Not entirely sure what I stumbled across as I'm no expert at JSON files, but here's what happened.

I'm on Windows 7 and downloaded the latest release of Brackets (1.2 I believe) and installed the autoprefixer extension. After playing around with it for a while and saving and re-saving css files I could not get it to prefix my css. I could see the options in the Edit menu but it's as if the extension itself just wasn't going.

Eventually I found the brackets.json file which had the autoprefixer settings in it, which were written like this:

` "mikaeljorhult.bracketsAutoprefixer.enabled": true,`

I looked at the package.json file for autoprefixer and saw that the name was written as:

`"mikaeljorhult.brackets-autoprefixer"`

So I changed all the preferences in brackets.json to `"mikaeljorhult.brackets-autoprefixer"` and now it's working perfectly. Not sure what would have caused this or if anyone else has experienced it but I thought it would be worth bringing up.

Thanks

**Comment by mikaeljorhult** [comment]
This should be resolved by version 0.6.0 that was just released.

**Comment by mikaeljorhult** [comment]
Upgrading and resetting settings have solved related problems (see #38).
Please reopen if you're still experience problems.
