### ISSUE TITLE
Nothing happens when saving CSS file or clicking auto prefix selection

### ISSUE THREAD

**Issue by bengoldman** [mikaeljorhult/brackets-autoprefixer#39]
I am having the same issue as previously reported by others.  This extension will not work for me at all.  Nothing happens when I save, or when I select auto prefix selection.  I am on a Mac.  Thanks.

**Comment by mikaeljorhult** [comment]
This should be resolved by version 0.6.0 that was just released.

**Comment by mikaeljorhult** [comment]
Upgrade and resetting the settings have worked for the others reporting this (see #38).
Please reopen if you're still having problems.
