### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by diazgilberto** [mikaeljorhult/brackets-autoprefixer#40]
I have Emmet install in brackets and I am planning to use Grunt in a project. Do I am going to have double prefixe in my code? prefixe from emmet and prefixe from autoprefixer when grunt compiles?

**Comment by mikaeljorhult** [comment]
The Autoprefixer package only add prefixes when needed and won't duplicate them. But if you're using Grunt for compiling your stylesheets I would setup [Autoprefixer through Grunt](https://github.com/postcss/autoprefixer#gulp). That way you have all your configuration in one place.

**Comment by diazgilberto** [comment]
Thank you for the replay.

Respectfully
Gilbert Díaz
