### ISSUE TITLE
Autoprefix on save not working

### ISSUE THREAD

**Issue by nickfmc** [mikaeljorhult/brackets-autoprefixer#41]
win8.1 brackets 1.3 when autoprefix on save is enabled nothing happens on save, still have to highlight selection and select prefix selection.

**Comment by mikaeljorhult** [comment]
What version of the extension are you using?

**Comment by HamburgerTS** [comment]
Same problem here. Version 0.6.0 (installed via extension manager)

**Comment by HamburgerTS** [comment]
Forgot: Brackets Release 1.3 Build 1.3.0-16022 (release cd0a6aae5)

**Comment by nikwins** [comment]
Same for me. Using Version 0.6.1 and Bracket Version 1.4. 
Autoprefixing only works with a selection, not on save.

**Comment by ammichael** [comment]
Here is not working with Brackets 1.4, version 0.6.1. I need to select and prefix selection

**Comment by mikaeljorhult** [comment]
That is usually a problem with syntax. The library will not parse the CSS if there is a syntax error or trying to prefix nested rules in Sass (sadly not supported in the Autoprefixer library).

**Comment by gasca1994** [comment]
Hello, I write from Colombia. I have a problem with autoprefixer.  I'm using it in Sass, But this does not complete the properties  I have installed it 3 time,but it does not work, i am using version 0.7.4

**Comment by mikaeljorhult** [comment]
Unfortunately the Autoprefixer library don't support Sass so you will have to autoprefix the compiled CSS files.
