### ISSUE TITLE
Autoprefix does not update exisiting prefixes

### ISSUE THREAD

**Issue by xycris** [mikaeljorhult/brackets-autoprefixer#43]
Hi,

I have existing code and ran autoprefixer and is happy with the result. However, I edited a number of codes that requires prefixing but when I ran autoprefix, the existing prefixes' value remained the same. Is this a bug or was it not a feature included in this extension?

Thanks.

**Comment by mikaeljorhult** [comment]
The Autoprefixer library only add and remove needed prefixes, it does not change any values.

I've been thinking about adding this as a feature but not gotten around to it. Please comment in the original issue (#15) so I can track the interest in a such feature.

**Comment by xycris** [comment]
hi mikael,

noted.

thanks again for this extension. looking forward to the progress of this.
