### ISSUE TITLE
Not working correctly for @-keyframes

### ISSUE THREAD

**Issue by Haelu** [mikaeljorhult/brackets-autoprefixer#44]
Instead of creating separate blocks for @-webkit-keyframes , @-moz-keyframes etc. which is required. This is only targeting what is inside the keyframes blocks and giving prefixed properties there. This does not show up in the CSS for the browsers.

**Comment by mikaeljorhult** [comment]
I've tested this in Brackets 1.4 with version 0.6.1 of the extension and it seems to be working.

Please try the latest version of the extension and reopen if you're still having any problems.
