### ISSUE TITLE
Unable to set target browsers

### ISSUE THREAD

**Issue by AllThingsSmitty** [mikaeljorhult/brackets-autoprefixer#45]
[Autoprefixer](https://github.com/postcss/autoprefixer) uses [Browserslist](https://github.com/ai/browserslist) so you can specify target browsers, e.g., > 1%, last 2 versions, etc. However, this Brackets plugin doesn't identify a way to target specific browsers. Is that feature in configuration or has it not been added?

**Comment by mikaeljorhult** [comment]
You're able to set which browsers to target in the settings dialog found in the Edit menu.
