### ISSUE TITLE
Autoprefixer(?) adds blank lines between vendor prefix rules when running the extension

### ISSUE THREAD

**Issue by BMOv2600** [mikaeljorhult/brackets-autoprefixer#46]
All the spacing among the order rules is brackets-autoprefixer's doing. 

Everything else is from Atom's autoprefixer pckg.

![too-much-space](http://i.imgur.com/P3weYgT.png)

Is this b/c of something in my config? Expected behavior?

**Comment by mikaeljorhult** [comment]
That looks like a configuration problem, Autoprefixer shouldn't do anything like that.
If it's still a problem please try the new version 0.6.2.
