### ISSUE TITLE
Autoprefixer not work on Arhlinux

### ISSUE THREAD

**Issue by DieterBuddenberg** [mikaeljorhult/brackets-autoprefixer#47]
When installing the extension Autoprefixer using brackets in Archlinux, this is not installed correctly and does not work, disables, or by the Manager extension brackets or Github.

Could Autoprefixer need any dependencies?

**Comment by mikaeljorhult** [comment]
All dependencies are included. Do you see any errors or warnings in the developer tools?

**Comment by Phantons** [comment]
I'm having the same problems when installing autoprefixer on ubuntu. It says 'The extension has encountered an error at startup' and i've tried to install autofixer in other ways like directly from the zip or from the link of github but nothing.
![brackets-autoprefixer-error](https://cloud.githubusercontent.com/assets/804054/11585807/dee69ec4-9a6e-11e5-8f82-d9d2b60175b7.png)

**Comment by mikaeljorhult** [comment]
That seems to be a problem with Brackets itself and not the extension. Have you tried downloading any other extension? Otherwise please try again with the just released version 0.6.2.

**Comment by mikaeljorhult** [comment]
@Phantons: Are you able to install other extensions?

**Comment by Phantons** [comment]
Sorry for not answer you before. I updated the extension and tried it out but the problem remains.  Yes, I show you in the screenshot below.
![brackets-error-2 copia](https://cloud.githubusercontent.com/assets/804054/13705693/367a4d36-e7a2-11e5-99f4-895445ef31bd.png)

**Comment by mikaeljorhult** [comment]
@Phantons: There is a new version available for download. Would you mind testing this Archlinux?

**Comment by leolembo** [comment]
Hi, i´m having the same problem trying to install autoprefixer in brackets, anyone know the solution?
Thanks!
