### ISSUE TITLE
Autoprefixer dosen't work on Brackets & Atom.

### ISSUE THREAD

**Issue by MehdiDehghani** [mikaeljorhult/brackets-autoprefixer#48]
Hi,
I'm using Windows 7 as OS, Latest version of Brackets & Atom, Installed latest version of Autoprefixer on that 2 IDEs (Brackets & Atom I mean), but Autoprefixer doesn't work.

Extra note: I'm using Visual Studio 2013 and Latest version of Web Essential, and turned Autoprefixer on, but there no effect of Autoprefixer.

What is wrong?

**Comment by reissy88** [comment]
Also not working for me, using Windows 10

**Comment by mikaeljorhult** [comment]
Please try the just released version 0.6.2. I've tested it successfully with Brackets 1.6 on OS X.

**Comment by mikaeljorhult** [comment]
Have you tried the latest version of the extension @MehdiDehghani @reissy88?

**Comment by MehdiDehghani** [comment]
I just tired on Atom (I know Atom's one  is not yours, just for info. atm I haven't brackets installed on my machine), and still doesn't work for me, maybe I should using gulp instead of extensions.
I'll post about it after trying gulp.
Thanks anyway.
