### ISSUE TITLE
Not able to get this extension working at all...

### ISSUE THREAD

**Issue by UlisesCL** [mikaeljorhult/brackets-autoprefixer#50]
Hi, I am not an expert on this whole Brackets editor, but I wanted to get this extension working and went ahead and installed it just like any other extension. 
I Ran a couple of scss lines (I use Scout, don't ask me why I just don't know how to compile sass with Brackets) but the compiled css shows no prefixes at all. I am on 'on save' mode btw and I use Brackets version 1.5
What am I missing here? any ideas? thank you in advance.

**Comment by sayhien** [comment]
same, using mac n brackets, couldnt get this to work, maybe time for an update mikael?

**Comment by mikaeljorhult** [comment]
Please try the newly released version, 0.6.2. I've tested it successfully on Brackets 1.6 on OS X.

**Comment by sayhien** [comment]
wow mikael i wasn't expecting you to fix this issue like 1 day after i wrote "maybe time for an update.."

yup it works now great job!

**Comment by mikaeljorhult** [comment]
Finally got some spare time to fix the issue. Hope the new version solved your problem.

**Comment by UlisesCL** [comment]
Thank you Mikael, all is good now!!
