### ISSUE TITLE
radial-gradient not working properly

### ISSUE THREAD

**Issue by Joci933** [mikaeljorhult/brackets-autoprefixer#53]
Hello,

The radial-gradient not prefixed properly.

The autoprefixer saved background: radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%) as: 
background: -webkit-radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%);

but, this not working on IE and firefox.

The correct syntax is this:
 background: -ms-radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%);
 background: -moz-radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%);
background: -webkit-radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%);
radial-gradient(48% 49%, circle cover, #2b2b2b 0, #181818 100%);

**Comment by mikaeljorhult** [comment]
Which browsers are you targeting (from the settings dialog)?

**Comment by mikaeljorhult** [comment]
@Joci933: Please reopen this issue if you've checked your target browser in the settings dialog and still is experience problems.
