### ISSUE TITLE
Visual Cascade not working

### ISSUE THREAD

**Issue by tjameswhite** [mikaeljorhult/brackets-autoprefixer#54]
Using auto prefix on selection, output is all one line, not stacked:

`display: -webkit-box;display: -webkit-flex;display: -ms-flexbox;display: flex;`

Toggling the Visual Cascade option makes no difference.  Would like code to appear stacked:

```
display: -webkit-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
```

Running Brackets build 1.5.0-16538; Autoprefixer v 0.6.2

**Comment by mikaeljorhult** [comment]
Have you tried using the latest version of Brackets (1.6)?

**Comment by tjameswhite** [comment]
No I have not. I had 1.6 briefly, but went back to 1.5 because of some issues. Right now, Beautify cleans it up nicely, it's just an extra step.

**Comment by mikaeljorhult** [comment]
Please reopen this issue if you have any problems after updating to version 1.6.
