### ISSUE TITLE
Support less files

### ISSUE THREAD

**Issue by MVyroubal** [mikaeljorhult/brackets-autoprefixer#56]
Hi, is possible to add support for file type less?
Thanks

**Comment by mikaeljorhult** [comment]
Unfortunately the Autoprefixer library (which this extension use) does not support Less or SASS. I'm looking into detecting CSS file changes (#35) to be able to work in tandem with preprocessors but it is not done yet.

If you need it right now I would go for a task runner like Gulp or Grunt to handle both preprocessing and autoprefixing.
