### ISSUE TITLE
Request: Auto-prefix with Precompiler

### ISSUE THREAD

**Issue by wkaskie** [mikaeljorhult/brackets-autoprefixer#57]
Hi,

I never write CSS anymore. This tool is fantastic, but I have to keep my scss and css files open to use it. I make my real changes, then make a fake change to CSS (add a space, remove a space) and save that to auto-prefix.

Without those extra steps, this would be PERFECT!

**Comment by mikaeljorhult** [comment]
@wkaskie: This feature is now in the master branch. Still got some testing before release but if you want to give it ago now please let me know if you run into any problems.

**Comment by wkaskie** [comment]
Fantastic! I will try it today!
