### ISSUE TITLE
Como configurar o autoprefixer

### ISSUE THREAD

**Issue by Luenilson** [mikaeljorhult/brackets-autoprefixer#58]
Gostaria de saber como configurar autoprefixer para adicionar outros navegadores

![13902775_145677285870109_6433344527797552384_n](https://cloud.githubusercontent.com/assets/20912870/17494155/d8a55f62-5d89-11e6-87b1-9cff75bcc025.jpg)

**Comment by kikeonline** [comment]
+1

**Comment by disgustinghuman** [comment]
>1% to >0%

**Comment by Capati** [comment]
Da uma olhada na [documentação do Browserlist](https://github.com/ai/browserslist#queries) para obter mais informações sobre queries e nomes dos navegadores.
