### ISSUE TITLE
Compiler sass + autoprefix in Bracket

### ISSUE THREAD

**Issue by sanpan93** [mikaeljorhult/brackets-autoprefixer#59]
- In brackets 1.7, i use Bracket-Sass to compile my .scss files into .css files : it works well
- i wonder if i can use auto-prefix when i save my .scss (to add prefix on .css files directly after saving my .scss files, so on change my .css files). 
- In issue #57, it seems to be possible but i don't know how. Do i have to add some line in my brackets.json ? Do i have to use some cmd in the topmenu of brackets ? In this topmenu, in item Edit/ i only have autoprefix on save / selection / préference. Nothing about on change.

**Comment by mikaeljorhult** [comment]
Prefixing changed files was in the pre-release (as described in #57) but is also in the main release as of version 0.7.0 which was released today.
