### ISSUE TITLE
Questions about Auroprefixer preferences in Brackets

### ISSUE THREAD

**Issue by humandesign01** [mikaeljorhult/brackets-autoprefixer#60]
Hi there,
I'm not sure what to do with the setting, should I just leave it to the default or should I manually insert all the  browsers name in the list. Thank you in advance for the reply

This is my current setting at the moment, am I doing it right?
![apx](https://cloud.githubusercontent.com/assets/23723516/20602349/7c04ad7a-b28f-11e6-86b6-53c05319379f.jpg)

**Comment by mikaeljorhult** [comment]
Yes, that will work fine. Autoprefixer is using [Browserlist](https://github.com/ai/browserslist) to target browser so all its supported queries will work.
