### ISSUE TITLE
Not working with Brackets 1.9 on window 7 machine.

### ISSUE THREAD

**Issue by Northout-Salman** [mikaeljorhult/brackets-autoprefixer#61]
@mikaeljorhult 
i'm new to this extension, can u please tell me how to use it.
i'm selecting my css code like this
 ` display: block;
    padding: 1.2em 30px;
    text-decoration: none;
    background: rgba(0,0,0,.95);
    color: #fff;
    font-size: 12px;
    float: left;
    width: 100%;
   text-transform: uppercase;
  font-family: 'montserratsemi_bold';`
and its not working

**Comment by mikaeljorhult** [comment]
Are you including the selector in the selection?

**Comment by Northout-Salman** [comment]
Hey @mikaeljorhult
thanks for the reply.
did you mean i have to select css code like this
`.somediv {display: block; padding: 1.2em 30px; text-decoration: none; background: rgba(0,0,0,.95); color: #fff; font-size: 12px; float: left; width: 100%; text-transform: uppercase; font-family: 'montserratsemi_bold';}`
or can you please make a quick video/gif of working this extension, its my request if its possible. we have some many autoprefixer available on internet. but i like to use brackets so it will be best if i use this extension.

Thanks again

**Comment by mikaeljorhult** [comment]
Yes, exactly. You need to include the selector and the curly brackets.

**Comment by Northout-Salman** [comment]
@mikaeljorhult
still not working see attached link
[http://35.164.205.197/assets/vendor/theme/images/issue.gif](url)

**Comment by Northout-Salman** [comment]
[http://35.164.205.197/assets/vendor/theme/images/issue.gif](url)

**Comment by Northout-Salman** [comment]
@mikaeljorhult 
Please copy paste this link in your browser, and please let me know what i'm forgetting. I tried enable/disable extension in brackets. restarted brackets after installiing extension, but still not working. i have recorded a gif of my screen have a look.
http://35.164.205.197/assets/vendor/theme/images/issue.gif

**Comment by mikaeljorhult** [comment]
Great!
