### ISSUE TITLE
Custom settings broken since Brackets update 1.9 ?

### ISSUE THREAD

**Issue by pieter-biesemans** [mikaeljorhult/brackets-autoprefixer#62]
Since the last update of brackets, Release build 1.9, custom settings seem to be broken.

Whenever I open the Autoprefixer settings I get [object Object] in the browser list instead of the usual list. I made a screenshot to illustrate the issue.
If I then proceed to fill out the list correctly and click 'OK' the window closes. But then when I open the Settings window again, it says [object Object] again.

Code is still being prefixed with the default prefixes (e.g. -webkit-transform) but not with custom ones (e.g. ms-transform).

If need be I can test this issue further by re-installing the extension and/or Brackets, or uninstalling other extensions.

![image](https://cloud.githubusercontent.com/assets/11043199/24413002/6706c672-13da-11e7-94a9-2b1306973930.png)

**Comment by mikaeljorhult** [comment]
Thank you for reporting this. I haven't had a chance to test on version 1.9 yet. I will try to get to that as soon as possible.

**Comment by mikaeljorhult** [comment]
Couldn't help myself and started troubleshooting right away. There was a small change in how preferences were cast. Released a new version that fix this.

Thanks again for reporting it!
