### ISSUE TITLE
Autoprefix stopped working on file save

### ISSUE THREAD

**Issue by CraigMac1000** [mikaeljorhult/brackets-autoprefixer#65]
Hello! Great plugin btw! I have just developed an issue so I hope you can help...

Looks like this issue is old now as I have seen it in issue #38 but I have developed the same issue recently. Autoprefix is fine when you use it manually Ctrl+shift+P but the autoprefix on save has just stopped working. I recently updated to v1.9 of brackets but have since rolled back to v1.8 but the issue is still there. Any ideas?

**Comment by mikaeljorhult** [comment]
Those kinds of issues are usually caused by some error in the CSS file preventing Autoprefixer from parsing it correctly. Do you experience it on all files?

**Comment by CraigMac1000** [comment]
Wow! I feel like such a noob! It's fine when I opened another css faile and traied it... Thanks. You can close this now. Now I need to find the error in 1562 lines of css. How hard can it be! :D

**Comment by mikaeljorhult** [comment]
That's okay, happens to all of us! =)

The extension should be displaying these kinds of errors to the user but I have yet to figure out a good way to do it.
