### ISSUE TITLE
What to do to use other prefixes

### ISSUE THREAD

**Issue by anandisrocking007** [mikaeljorhult/brackets-autoprefixer#71]
Hello sir i like your extension but i can not understand what do i have to add in the settings to get prefiexes for  -moz-  and -o- as of now it only gives out -webkit- and any editing to the settings would not make the extension give out even that.

**Comment by pieter-biesemans** [comment]
This is just a Brackets extension to wrap [Autoprefixer](https://github.com/postcss/autoprefixer). This library in turn uses Browserlist to determine which prefixes to use. You can take a look at possible settings for Browserlist [here](https://github.com/ai/browserslist#queries). You can add these queries in the Autoprefixer Settings dialog in Brackets (Edit > Autoprefixer Settings...)

For example, if you wanted to include the -moz- prefix for Mozilla browsers, you could add **Firefox > 20** for versions of Firefox newer than 20.

![image](https://user-images.githubusercontent.com/11043199/32442962-a3390f60-c2fd-11e7-9fa8-cacde148e3f3.png)

**Comment by mikaeljorhult** [comment]
Thank you for helping out @pieter-biesemans. @anandisrocking007 Just like Pieter described - specify the browser versions you wish to support and the library will automatically add the prefixes needed for that.
