### ISSUE TITLE
Auto prefix css file compiled by Less plugin

### ISSUE THREAD

**Issue by remayex** [mikaeljorhult/brackets-autoprefixer#74]
Hi, I use bracket along with Less and Autoprefixer plugins.
I selected "Auto prefix on save" in the edit menu but when I save the .less file that produce the .css file, Autoprefixer is not triggered.
Is there any way, using some command in the Less plugin .json file or somewhere else to trigger Autoprefixer anytime .css file has changed ?
Thanks.

**Comment by JulioPolo** [comment]
I use sass and just enabled "auto prefix when file changed" on the "edit" menu and it works.

**Comment by mikaeljorhult** [comment]
Thanks for helping out @JulioPolo! It should work in the way described.
